kind: Route
apiVersion: v1
metadata:
  name: wordpress-route
spec:
  host: www.kaseb.xyz
  to:
    kind: Service
    name: wordpress-svc
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  port:
    targetPort: http
