- hosts: nl1
  become: true

  tasks:
    - name: copy env file to server
      copy:
        src: secret-env
        dest: /secret-env
      tags:
        - env

    - name: copy docker-compose to server
      copy:
        src: docker-compose.yml
        dest: /docker-compose.yml
      tags:
        - compose

    - name: copy squid config to server
      copy:
        src: ../../squid/squid-conf
        dest: /data/squid/conf
      tags:
        - squid

    - name: copy squid user to server
      copy:
        src: ../../squid/squid_users
        dest: /data/squid/squid_users
      tags:
        - squid

    - name: copy nginx config to server
      copy:
        src: nginx/default.conf
        dest: /data/nginx/nginx/site-confs/default
      tags:
        - nginx

    - name: copy nginx secret to server
      copy:
        src: nginx/htpasswd
        dest: /data/nginx/
      tags:
        - nginx

    - name: copy prometheus to server
      copy:
        src: prometheus
        dest: /data
      tags:
        - prom

    - name: copy alertmanager to server
      copy:
        src: ../../alertmanager
        dest: /data
      tags:
        - alert

    - name: copy grafana to server
      copy:
        src: ../../grafana
        dest: /data
      tags:
        - grafana

    - name: copy fluent to server
      copy:
        src: fluent
        dest: /data
      tags:
        - fluent

    - name: run docker-compose
      docker_compose:
        project_src: /
        pull: no
      tags:
        - compose
        - up
