version: "3.8"
services:
  postgres:
    image: postgres:12.3
    restart: unless-stopped
    container_name: postgres
    ports:
      - 5436:5432
    env_file:
      - secret-env
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    networks:
      - postgres

  pgbackups3:
    image: amirabbas/postgres-backup-s3
    container_name: pgbackups3
    environment:
      - SCHEDULE=@daily
      - S3_ENDPOINT=https://s3.ir-thr-at1.arvanstorage.com
      - S3_BUCKET=pg-prod-backup
      - S3_PREFIX=backup
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=kaseb
      - POSTGRES_USER=admin
      - POSTGRES_EXTRA_OPTS=--schema=public --blobs
    env_file:
      - secret-env
    networks:
      - postgres
    depends_on:
      - postgres
    labels:
      dozzle: "show logs"

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=wordpress
    env_file:
      - secret-env
    volumes:
      - /data/mysql:/var/lib/mysql
    networks:
      - mysql

  mybackups3:
    image: schickling/mysql-backup-s3
    container_name: mybackups3
    environment:
      - SCHEDULE=@weekly
      - S3_ENDPOINT=https://s3.ir-thr-at1.arvanstorage.com
      - S3_BUCKET=wordpress-backup
      - S3_PREFIX=backup
      - MYSQLDUMP_DATABASE=wordpress
      - MYSQL_USER=root
      - MYSQL_HOST=mysql
    env_file:
      - secret-env
    networks:
      - mysql
    depends_on:
      - mysql
    labels:
      dozzle: "show logs"

  elasticsearch:
    container_name: elasticsearch
    user: "1000:1000"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
    env_file:
      - secret-env
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch/data

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.37.0
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    restart: unless-stopped

  nodeexporter:
    image: prom/node-exporter:v1.0.1
    container_name: nodeexporter
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"

networks:
  postgres:
  mysql:
