version: "3.8"
services:
  postgres:
    image: postgres:12.3
    restart: unless-stopped
    container_name: postgres
    ports:
      - 5436:5432
    env_file:
      - secret-env
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    networks:
      - postgres

  pgbackups3:
    image: amirabbas/postgres-backup-s3
    container_name: pgbackups3
    environment:
      - SCHEDULE=@daily
      - S3_ENDPOINT=https://s3.ir-thr-at1.arvanstorage.com
      - S3_BUCKET=pg-prod-backup
      - S3_PREFIX=backup
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=kaseb
      - POSTGRES_USER=admin
      - POSTGRES_EXTRA_OPTS=--schema=public --blobs
    env_file:
      - secret-env
    networks:
      - postgres
    depends_on:
      - postgres
    labels:
      dozzle: "show logs"

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=wordpress
    env_file:
      - secret-env
    volumes:
      - /data/mysql:/var/lib/mysql
    networks:
      - mysql

networks:
  postgres:
  mysql:
