- hosts: mn1
  become: true

  tasks:
    - name: copy env file to server
      copy:
        src: secret-env
        dest: /secret-env
      tags:
        - env

    - name: copy docker-compose to server
      copy:
        src: docker-compose.yml
        dest: /docker-compose.yml
      tags:
        - compose

    - name: copy fluent to server
      copy:
        src: fluent
        dest: /data
      tags:
        - fluent

    - name: run docker-compose
      docker_compose:
        project_src: /
        pull: no
      tags:
        - compose
        - up
