version: "3"

services:
  harness-cli:
    container_name: harness-cli
    image: actionml/harness-cli:develop
    environment:
      PATH: "$PATH:/harness-cli/harness-cli"
      HARNESS_SERVER_ADDRESS: 37.152.187.66
    volumes:
      - .:/configs
