global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "my-project"

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-server"
    metrics_path: "/monitoring/prometheus"
    scrape_interval: 10s
    basic_auth:
      username: kaseb
      password_file: password
    static_configs:
      - targets:
          - "server:1212"
          - "api-kaseb.apps.ir-thr-at1.arvan.run"

  - job_name: "tracking-server"
    metrics_path: "/monitoring/prometheus"
    scrape_interval: 10s
    basic_auth:
      username: kaseb
      password_file: password
    static_configs:
      - targets:
          - "tracking-server:1313"
          - "track-kaseb.apps.ir-thr-at1.arvan.run"

  - job_name: "nodeexporter"
    scrape_interval: 10s
    basic_auth:
      username: kaseb
      password_file: password-prod
    static_configs:
      - targets: ["nodeexporter:9100", "node.kaseb.xyz"]

  - job_name: "cadvisor"
    scrape_interval: 10s
    basic_auth:
      username: kaseb
      password_file: password-prod
    static_configs:
      - targets: ["cadvisor:8080", "cadvisor.kaseb.xyz"]
